# Site settings
title: Van Mobile Apps
email: vanmobileapp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "MobileApps" # the subpath of your site, e.g. /blog/
url: "https://vanmobile.github.io" # the base hostname & protocol for your site

twitter_username: reactivizer
github_username: VanMobile

# Build settings
markdown: kramdown
